"""Instantiate an empty course from this vault's scaffolding.

Lane E of `docs/PLAN-academy-template-and-ev3.md`. The owner never touches git
template mechanics; this script is the whole interface.

What it does: create the stage tree, write a validated `course.yaml`, write a
`topology.md` derived from that manifest, and prove the result loads. What it
must never do: copy course CONTENT. A scaffolder that copies one course's
lessons into the next one produces a vault that looks populated and is wrong,
and the wrongness is invisible until a child reads a micro:bit slide in an EV3
lesson.

Refusals, all of them deliberate:

* a non-empty target — never merge into someone's work
* a target inside the source vault — a course nested in a course has two
  manifests above every bundle, and `discovery_for` walks upward
* any network access — there is none in this module, by construction
* a manifest it cannot load back — writing an invalid manifest and reporting
  success is the fail-open this vault keeps finding
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

from . import config

# Copied verbatim into a new course. Code and schemas only: no lesson content,
# no assets, no research, no receipts. Everything here is course-neutral or is
# a template with placeholders.
SCAFFOLD_FILES = (
    "pyproject.toml",
    "00-contracts/brand-and-output.md",
    "00-contracts/rubric.md",
    "75-bundle/_TEMPLATE-blueprint.md",
    "75-bundle/_TEMPLATE-debugging-lab.md",
)
SCAFFOLD_DIRS = (
    "scripts",
    "tests",
)
# Created empty. These are where a course's own work accumulates.
STAGE_DIRS = (
    "10-digest",
    "20-provenance",
    "30-research",
    "40-critique",
    "50-patch",
    "55-refuted",
    "60-approved",
    "70-localized",
    "75-bundle",
    "80-generation",
    "90-receipts",
    "knowledge",
)

_SLUG = re.compile(r"[a-z][a-z0-9-]{1,63}")


class ScaffoldError(RuntimeError):
    """The course could not be created. Never partially reported as success."""


@dataclass(frozen=True)
class Seed:
    """Everything about a new course that is not derivable from the template."""

    slug: str
    name: str
    levels: tuple[int, ...]
    sessions_per_level: int
    providers: tuple[str, ...]
    artifact_schedule: tuple[bool, ...]
    asset_ref_pattern: str
    asset_source_files: tuple[str, ...]
    expect_references: bool

    def validate(self) -> None:
        if not _SLUG.fullmatch(self.slug):
            raise ScaffoldError(
                f"slug {self.slug!r} must be lowercase letters, digits and hyphens"
            )
        if len(self.artifact_schedule) != self.sessions_per_level:
            raise ScaffoldError(
                f"artifact_schedule has {len(self.artifact_schedule)} entries for "
                f"{self.sessions_per_level} sessions per level — one per session, in order"
            )


def manifest_text(seed: Seed) -> str:
    """The course.yaml body. Written through yaml.safe_dump, never f-strings.

    Hand-built YAML is how a regex containing a backslash or a colon becomes a
    parse error in a file nobody reads until a gate fails.
    """
    doc = {
        "levels": list(seed.levels),
        "sessions_per_level": seed.sessions_per_level,
        "providers": list(seed.providers),
        "artifact_schedule": {
            f"s{n}": bool(v) for n, v in enumerate(seed.artifact_schedule, start=1)
        },
        "stages": {
            "digest": "10-digest",
            "digest_assets": "_assets",
            "provenance": "20-provenance",
            "receipts": "90-receipts",
        },
        "asset_discovery": {
            "asset_ref_pattern": seed.asset_ref_pattern,
            "asset_source_files": list(seed.asset_source_files),
            "expect_references": seed.expect_references,
        },
    }
    header = (
        f"# {seed.name}\n"
        f"# Generated by scripts/swarm/new_course.py. The single runtime manifest:\n"
        f"# every script reads this rather than hardcoding a course's shape.\n"
    )
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)


def topology_text(seed: Seed, course: config.CourseConfig) -> str:
    """Derived from the loaded manifest, not from the seed.

    Reading it back is the point: a topology generated from the seed would agree
    with the seed even when the manifest on disk says something else.
    """
    lines = [
        f"# {seed.name} — topology",
        "",
        "Generated from `course.yaml`. Do not edit by hand; edit the manifest.",
        "",
        f"- levels: {', '.join(str(n) for n in course.levels)}",
        f"- sessions per level: {course.sessions_per_level}",
        f"- providers: {', '.join(sorted(course.providers))}",
        "",
        "| Session | Artifacts |",
        "| --- | --- |",
    ]
    for level in course.levels:
        for n in range(1, course.sessions_per_level + 1):
            sid = f"L{level}-s{n}"
            lines.append(f"| {sid} | {'yes' if course.produces_artifacts(sid) else 'no'} |")
    lines.append("")
    return "\n".join(lines)


def _check_target(target: Path, source: Path) -> None:
    target = Path(target)
    source = Path(source).resolve()
    if target.exists() and any(target.iterdir()):
        raise ScaffoldError(
            f"{target} is not empty. Refusing to scaffold into existing work — "
            "choose an empty directory or move what is there."
        )
    resolved = target.resolve() if target.exists() else target.absolute()
    try:
        resolved.relative_to(source)
    except ValueError:
        return
    raise ScaffoldError(
        f"{target} is inside the source vault {source}. A course nested in a course "
        "puts two manifests above every bundle, and discovery resolves the nearer "
        "one — the new course would silently govern the old one's assets."
    )


def _copy_scaffold(source: Path, target: Path) -> list[str]:
    copied: list[str] = []
    for rel in SCAFFOLD_DIRS:
        src = source / rel
        if not src.is_dir():
            raise ScaffoldError(f"scaffold directory {rel!r} is missing from {source}")
        shutil.copytree(
            src,
            target / rel,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".pytest_cache"),
        )
        copied.append(rel + "/")
    for rel in SCAFFOLD_FILES:
        src = source / rel
        if not src.is_file():
            raise ScaffoldError(f"scaffold file {rel!r} is missing from {source}")
        dst = target / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
        copied.append(rel)
    return copied


def create(seed: Seed, target: Path, source: Path) -> config.CourseConfig:
    """Create the course and return the manifest as loaded back from disk."""
    seed.validate()
    target = Path(target)
    _check_target(target, source)

    target.mkdir(parents=True, exist_ok=True)
    for rel in STAGE_DIRS:
        (target / rel).mkdir(parents=True, exist_ok=True)
    _copy_scaffold(Path(source), target)

    (target / "course.yaml").write_text(manifest_text(seed), encoding="utf-8")

    # Load it BACK. Writing a manifest and reporting success without reading it
    # is exactly the shape of defect this vault has rejected five times.
    try:
        course = config.load_course(target)
    except config.CourseConfigError as exc:
        raise ScaffoldError(
            f"the generated manifest does not load: {exc}. The course directory is "
            "left in place for inspection; it is not usable."
        ) from exc

    (target / "topology.md").write_text(topology_text(seed, course), encoding="utf-8")
    return course


def _seed_from_args(ns: argparse.Namespace) -> Seed:
    schedule = tuple(
        n not in set(ns.no_artifact_sessions) for n in range(1, ns.sessions_per_level + 1)
    )
    return Seed(
        slug=ns.slug,
        name=ns.name or ns.slug,
        levels=tuple(ns.levels),
        sessions_per_level=ns.sessions_per_level,
        providers=tuple(ns.providers),
        artifact_schedule=schedule,
        asset_ref_pattern=ns.asset_ref_pattern,
        asset_source_files=tuple(ns.asset_source_files),
        expect_references=not ns.no_expect_references,
    )


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        prog="new_course.py",
        description="Create an empty course from this vault's scaffolding.",
    )
    ap.add_argument("slug", help="lowercase course slug, e.g. kids-ev3")
    ap.add_argument("target", type=Path, help="empty directory to create the course in")
    ap.add_argument("--name", default=None, help="human course name")
    ap.add_argument("--levels", type=int, nargs="+", default=[1, 2])
    ap.add_argument("--sessions-per-level", type=int, default=8)
    ap.add_argument(
        "--no-artifact-sessions",
        type=int,
        nargs="*",
        default=[8],
        help="session numbers that produce no artifacts (default: the graduation session)",
    )
    ap.add_argument(
        "--providers", nargs="+", default=["claude", "codex", "opencode", "hermes"]
    )
    ap.add_argument(
        "--asset-ref-pattern",
        required=True,
        help="regex with EXACTLY ONE capture group: the asset filename as referenced",
    )
    ap.add_argument("--asset-source-files", nargs="+", required=True)
    ap.add_argument(
        "--no-expect-references",
        action="store_true",
        help="allow a bundle to reference no assets at all (rare; usually a typo'd pattern)",
    )
    ap.add_argument(
        "--source",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="vault to copy scaffolding from (default: this one)",
    )
    ns = ap.parse_args(argv[1:])

    try:
        course = create(_seed_from_args(ns), ns.target, ns.source)
    except ScaffoldError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 2

    sessions = len(course.levels) * course.sessions_per_level
    with_artifacts = sum(
        course.produces_artifacts(f"L{lv}-s{n}")
        for lv in course.levels
        for n in range(1, course.sessions_per_level + 1)
    )
    print(f"created {ns.target}")
    print(f"  {sessions} session(s), {with_artifacts} producing artifacts")
    print(f"  providers: {', '.join(sorted(course.providers))}")
    print("  course.yaml validated by load_course; topology.md derived from it")
    print("\nNo course content was copied. The stage directories are empty on purpose.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main(sys.argv))
