"""Create the stage folders and write the machine-readable topology contract."""

from __future__ import annotations

import sys
from pathlib import Path

from swarm.paths import VAULT_ROOT

STAGE_DIRS: tuple[str, ...] = (
    "00-contracts",
    "10-digest",
    "20-provenance",
    "30-research",
    "40-critique",
    "50-patch",
    "55-refuted",
    "60-approved",
    "70-localized",
    "75-bundle",
    "80-generation",
    "90-receipts",
)

TOPOLOGY: dict[str, dict] = {
    "00-contracts": {"owner": "claude", "fanout": (), "writes": "one file per contract"},
    "10-digest": {"owner": "script", "fanout": (), "writes": "one file per session"},
    "20-provenance": {"owner": "hermes", "fanout": (), "writes": "one file per session"},
    "30-research": {
        "owner": "claude",
        "fanout": ("hermes", "codex", "opencode"),
        "writes": "_lanes/<cluster>/<provider>.json, merged to <cluster>.md",
    },
    "40-critique": {
        "owner": "claude",
        "fanout": ("codex", "opencode", "hermes"),
        "writes": "<session>/<provider>.json",
    },
    "50-patch": {"owner": "codex", "reviewer": "claude", "fanout": (), "writes": "one file per session"},
    "55-refuted": {"owner": "codex", "reviewer": "claude", "fanout": (), "writes": "one file per session"},
    "60-approved": {"owner": "codex", "reviewer": "claude", "fanout": (), "writes": "one file per session"},
    "70-localized": {"owner": "claude", "fanout": (), "writes": "one file per session"},
    "75-bundle": {"owner": "claude", "fanout": (), "writes": "one folder per session: trainer-guide.md, decisions.md, assets/, SOURCES.md"},
    "80-generation": {"owner": "claude", "fanout": (), "writes": "prompts and rendered output (NotebookLM MCP is claude-only)"},
    "90-receipts": {"owner": "script", "fanout": (), "writes": "<session>.<gate>.yaml"},
}


def scaffold(root: Path) -> list[Path]:
    """Create every stage directory. Idempotent."""
    created = []
    for name in STAGE_DIRS:
        path = root / name
        path.mkdir(parents=True, exist_ok=True)
        created.append(path)
    return created


def render_topology() -> str:
    """Machine-readable ownership map for 00-contracts/topology.md."""
    lines = [
        "# Swarm Topology",
        "",
        "Generated by `scripts/scaffold_vault.py`. Do not hand-edit.",
        "",
        "One writer per file, never one writer per folder.",
        "",
        "| stage | owner | reviewer | fan-out | writes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in STAGE_DIRS:
        t = TOPOLOGY[name]
        fanout = ", ".join(t["fanout"]) if t["fanout"] else "—"
        reviewer = t.get("reviewer", "—")
        lines.append(f"| `{name}` | {t['owner']} | {reviewer} | {fanout} | {t['writes']} |")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    root = VAULT_ROOT
    scaffold(root)
    (root / "00-contracts" / "topology.md").write_text(render_topology(), encoding="utf-8")
    print(f"scaffolded {len(STAGE_DIRS)} stage dirs under {root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
